In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
# load csv file
df = pd.read_csv('synthetic_data.csv')

# check the first few rows
print(df.head())

  Country  Age    Salary  Purchase
0  Canada   19  807572.0     False
1   India   32  176316.0      True
2  Brazil   23  649176.0     False
3     USA   19  128246.0      True
4   India   50       NaN      True


In [16]:
# load the data into numpy arrays
X = df.iloc[:, :-1].values
y = df.iloc[:, 3].values
print(X)

[['Canada' 19 807572.0]
 ['India' 32 176316.0]
 ['Brazil' 23 649176.0]
 ['USA' 19 128246.0]
 ['India' 50 nan]
 ['Brazil' 30 780800.0]
 ['India' 46 647889.0]
 ['USA' 66 874962.0]
 ['France' 39 321369.0]
 ['India' 66 382944.0]]


In [17]:
# perform preprocessing
from sklearn.impute import SimpleImputer

# assuming x is your data with missing values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

print(X)


[['Canada' 19.0 807572.0]
 ['India' 32.0 176316.0]
 ['Brazil' 23.0 649176.0]
 ['USA' 19.0 128246.0]
 ['India' 50.0 529919.3333333334]
 ['Brazil' 30.0 780800.0]
 ['India' 46.0 647889.0]
 ['USA' 66.0 874962.0]
 ['France' 39.0 321369.0]
 ['India' 66.0 382944.0]]


In [18]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Extract the categorical feature (Country) from the encoding 
countries = X[:, 0].reshape(-1, 1)

# Applying OneHotEncoder
onehotencoder = OneHotEncoder()
countries = onehotencoder.fit_transform(countries).toarray()

# Combine the encoded countries with the rest of the data
X_encoded = np.concatenate((countries, X[:, 1:]), axis=1) # axis=1 means concatenate columns

print("Encoded Dataset:")
print(X_encoded)

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print("\nEncoded Dependent Variable:")
print(y)


Encoded Dataset:
[[0.0 1.0 0.0 0.0 0.0 19.0 807572.0]
 [0.0 0.0 0.0 1.0 0.0 32.0 176316.0]
 [1.0 0.0 0.0 0.0 0.0 23.0 649176.0]
 [0.0 0.0 0.0 0.0 1.0 19.0 128246.0]
 [0.0 0.0 0.0 1.0 0.0 50.0 529919.3333333334]
 [1.0 0.0 0.0 0.0 0.0 30.0 780800.0]
 [0.0 0.0 0.0 1.0 0.0 46.0 647889.0]
 [0.0 0.0 0.0 0.0 1.0 66.0 874962.0]
 [0.0 0.0 1.0 0.0 0.0 39.0 321369.0]
 [0.0 0.0 0.0 1.0 0.0 66.0 382944.0]]

Encoded Dependent Variable:
[0 1 0 1 1 0 0 1 1 1]


In [19]:
from sklearn.model_selection import train_test_split

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=0)

print("\nTraining Set:")
print(X_train)
print(y_train)

print("\nTest Set:")
print(X_test)
print(y_test)


Training Set:
[[0.0 0.0 0.0 1.0 0.0 50.0 529919.3333333334]
 [0.0 0.0 0.0 1.0 0.0 66.0 382944.0]
 [0.0 0.0 0.0 1.0 0.0 32.0 176316.0]
 [0.0 0.0 0.0 1.0 0.0 46.0 647889.0]
 [0.0 0.0 0.0 0.0 1.0 66.0 874962.0]
 [0.0 0.0 0.0 0.0 1.0 19.0 128246.0]
 [0.0 1.0 0.0 0.0 0.0 19.0 807572.0]
 [1.0 0.0 0.0 0.0 0.0 30.0 780800.0]]
[1 1 1 0 1 1 0 0]

Test Set:
[[1.0 0.0 0.0 0.0 0.0 23.0 649176.0]
 [0.0 0.0 1.0 0.0 0.0 39.0 321369.0]]
[0 1]
