In [2]:
# basic python array operations

# create an array
arr = [1, 2, 3, 4, 5]

# print the array
print(arr)

# access the first element
print(arr[0])

# access the last element
print(arr[-1])

# access the second last element
print(arr[-2])

# access the first two elements
print(arr[0:2])

# access the last two elements
print(arr[-2:])

# access the elements from 2 to 4
print(arr[1:4])

# access the elements from 2 to 4 with a step of 2
print(arr[1:4:2])

# access the elements from 2 to 4 with a step of 3
print(arr[1:4:3])

# create a new array with the first two elements
new_arr = arr[:2]
print(new_arr)

# create a new array with the last two elements
new_arr = arr[-2:]


[1, 2, 3, 4, 5]
1
5
4
[1, 2]
[4, 5]
[2, 3, 4]
[2, 4]
[2]
[1, 2]


In [3]:
# numpy array operations
import numpy as np

# create a numpy array
arr = np.array([1, 2, 3, 4, 5])

# print the array
print(arr)

# access the first element
print(arr[0])

# access the last element
print(arr[-1])

[1 2 3 4 5]
1
5


In [5]:
# create numpy matrix

# create a 3x3 array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# print the array
print("The array:")
print(arr)

# Slicing to extract a subarray
sub_arr = arr[0:2, 1:]

print("Subarray:")  # print the subarray
print(sub_arr)


The array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Subarray:
[[2 3]
 [5 6]]
